# Development configuration for local Shopify CLI
# This file is used when running `npm run dev` locally
# It uses Cloudflare tunnels for local development

client_id = "6b383f96b244212bf8df47d0e0684aea"
name = "nupo-chatbot-dev"
application_url = "https://localhost:3000"
embedded = true
handle = "nupo-chatbot-dev"

[build]
include_config_on_deploy = false
automatically_update_urls_on_dev = true
dev_store_url = "your-dev-store.myshopify.com"

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
scopes = "read_products,write_products,read_orders,write_orders,read_customers,write_customers,read_discounts,write_discounts,read_shipping,write_shipping"

[auth]
redirect_urls = [
  "https://localhost:3000/auth/callback",
  "https://localhost:3000/auth/shopify/callback", 
  "https://localhost:3000/api/auth/callback"
]

[pos]
embedded = false
