# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6b383f96b244212bf8df47d0e0684aea"
name = "nupo-chatbot"
application_url = "https://covering-legacy-attitudes-seal.trycloudflare.com"
embedded = true
handle = "nupo-chatbot"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_orders,write_orders,read_customers,write_customers,read_discounts,write_discounts,read_shipping,write_shipping"

[auth]
redirect_urls = [
  "https://covering-legacy-attitudes-seal.trycloudflare.com/auth/callback",
  "https://covering-legacy-attitudes-seal.trycloudflare.com/auth/shopify/callback",
  "https://covering-legacy-attitudes-seal.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
